image: gradle:5.4.1-jdk8

stages:
  - compile
  - publish
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: compile
  script:
    - gradle build

dockerBuild:
  stage: publish
  script:
    - docker info
    - gradle dockerBuildImage
dockerDeploy:
  stage: publish
  script:
    - docker run --restart=always --name pecker -p 443:443 -d pecker:latest
