CREATE TABLE APP_SERVER(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(32),
    HOST VARCHAR(64),
    PORT INT,
    DOMAIN VARCHAR(32),
    USERNAME VARCHAR(32),
    PASSWORD VARCHAR(32),
    DIR VARCHAR(128),
    TOKEN VARCHAR(64),
    REPO VARCHAR(64),
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE APP(
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64),
  IDENTIFIER VARCHAR(64),
  AGENT VARCHAR(32),
  SERVER INT,
  ALPHA VARCHAR(512),
  TRIAL VARCHAR(512),
  RELEASE VARCHAR(512),
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

